/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  // Stays 'class' (inert) until the last dark: class is removed in slice 07. Never 'media'.
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#137fec',
        'primary-dim': '#0048c1',
        'primary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#c7d3ff',
        'primary-container': '#dbe1ff',
        'on-primary': '#f8f7ff',
        'on-primary-container': '#0048bf',
        'on-primary-fixed': '#003798',
        'on-primary-fixed-variant': '#0050d4',
        secondary: '#506076',
        'secondary-dim': '#44546a',
        'secondary-fixed': '#d3e4fe',
        'secondary-fixed-dim': '#c5d6f0',
        'secondary-container': '#d3e4fe',
        'on-secondary': '#f7f9ff',
        'on-secondary-container': '#435368',
        'on-secondary-fixed': '#314055',
        'on-secondary-fixed-variant': '#4d5d73',
        tertiary: '#615b77',
        'tertiary-dim': '#554f6b',
        'tertiary-fixed': '#e3dbfd',
        'tertiary-fixed-dim': '#d5cdee',
        'tertiary-container': '#e3dbfd',
        'on-tertiary': '#fcf7ff',
        'on-tertiary-container': '#524c68',
        'on-tertiary-fixed': '#3f3a54',
        'on-tertiary-fixed-variant': '#5c5672',
        error: '#9f403d',
        'error-dim': '#4e0309',
        'error-container': '#fe8983',
        'on-error': '#fff7f6',
        'on-error-container': '#752121',
        background: '#f7f9fb',
        surface: '#f7f9fb',
        'surface-bright': '#f7f9fb',
        'surface-dim': '#cfdce3',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f4f7',
        'surface-container': '#e8eff3',
        'surface-container-high': '#e1e9ee',
        'surface-container-highest': '#d9e4ea',
        'surface-variant': '#d9e4ea',
        'surface-tint': '#0053db',
        'on-surface': '#2a3439',
        'on-surface-variant': '#566166',
        'on-background': '#2a3439',
        outline: '#717c82',
        'outline-variant': '#a9b4b9',
        'inverse-primary': '#618bff',
        'inverse-surface': '#0b0f10',
        'inverse-on-surface': '#9a9d9f',
        'background-light': '#f6f7f8',
        'background-dark': '#101922',
        // Role-based tokens. New and restyled UI uses only these.
        accent: '#0f766e',
        'accent-hover': '#115e59',
        link: '#005c55',
        action: '#213145',
        'action-hover': '#0b1c30',
        ink: '#0f172a',
        'ink-body': '#334155',
        'ink-muted': '#64748b',
        canvas: '#ffffff',
        subtle: '#f8fafc',
        line: '#e2e8f0',
        'line-strong': '#cbd5e1',
        selected: '#f0fdfa',
        status: {
          'teal-bg': '#f0fdfa',
          'teal-text': '#0f766e',
          'teal-border': '#99f6e4',
          'amber-bg': '#fffbeb',
          'amber-text': '#b45309',
          'amber-border': '#fde68a',
          'amber-dot': '#d97706',
          'red-bg': '#fef2f2',
          'red-text': '#b91c1c',
          'red-border': '#fecaca',
          'red-dot': '#dc2626',
          'slate-bg': '#f8fafc',
          'slate-text': '#334155',
          'slate-border': '#e2e8f0',
        },
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'page-title': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        section: ['18px', { lineHeight: '24px', letterSpacing: '-0.015em', fontWeight: '600' }],
        panel: ['15px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '600' }],
        body: ['13px', { lineHeight: '18px', letterSpacing: '-0.005em' }],
        small: ['12px', { lineHeight: '16px' }],
        label: ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
        badge: ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '500' }],
        // Legacy keys for pages not yet restyled. Removed in slice 07.
        'body-md': ['13px', { lineHeight: '18px' }],
        'label-md': ['13px', { lineHeight: '18px' }],
        'headline-sm': ['24px', { lineHeight: '32px' }],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
        badge: '3px',
      },
      boxShadow: {
        overlay: '0 4px 6px -1px rgba(15, 23, 42, 0.08), 0 2px 4px -2px rgba(15, 23, 42, 0.04)',
      },
      zIndex: {
        sticky: '10',
        header: '20',
        bulkbar: '30',
        dropdown: '40',
        popover: '40',
        modal: '50',
        confirm: '60',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
